name: Subply Pipeline #nama actionsnya
run-name: ${{ github.actor }} triggered pipeline
on:
  push:
    branches:
      - master #yang master-master aj
jobs:
  subply-deploy:
    runs-on: ubuntu-latest #os yang dipakai gh actions
    steps:
      - uses: actions/checkout@v4 #tool untuk clone current repo

      - name: Show info
        run: | #basically ambil data ni vm
          echo "OS: ${{ runner.os }}" 
          echo "Branch: ${{ github.ref }}"
          echo "Repo: ${{ github.repository }}"

      - name: LIst workspace files
        run: ls -la ${{github.workspace}}

      - name: build docker image # build image
        run: docker build -t subply-api:latest .

      - name: adding tags to image #nambah tag ke image
        run: | # tag untuk ghcr dan gcr
          docker tag subply-api:latest gcr.io/gcr-160603/subply-api:latest
          docker tag subply-api:latest ghcr.io/vhysxl/subply-api:latest

      - name: login ghcr # loginkan ghcr le
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: push to ghcr
        run: |
          docker push ghcr.io/vhysxl/subply-api:latest

      #todo : gcp (gae)
