name: Subply Pipeline #nama actionsnya
run-name: ${{ github.actor }} triggered pipeline
on:
  push:
    branches:
      - master #yang master-master aj
jobs:
  subply-deploy:
    runs-on: ubuntu-latest #os yang dipakai gh actions
    steps:
      - uses: actions/checkout@v4 #tool untuk clone current repo

      - name: Show info
        run: | #basically ambil data ni vm
          echo "OS: ${{ runner.os }}" 
          echo "Branch: ${{ github.ref }}"
          echo "Repo: ${{ github.repository }}"

      - name: LIst workspace files
        run: ls -la ${{github.workspace}}

      - name: build docker image # build image
        run: docker build -t subply-api:latest .

      - name: adding tags to image #nambah tag ke image
        run: | # tag untuk ghcr dan gcr
          docker tag subply-api:latest ghcr.io/${{github.actor}}/subply-api:latest

      - name: login ghcr # loginkan ghcr le
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: push to ghcr
        run: |
          docker push ghcr.io/${{github.actor}}/subply-api:latest

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/591941627936/locations/global/workloadIdentityPools/github-actions-subply/providers/github-provider'
          service_account: 'github-actions-subply@modified-fabric-379312.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'subply-deploy'
          image: 'ghcr.io/${{ github.actor }}/subply-api:latest'
          region: 'asia-southeast2'
          project: 'modified-fabric-379312'
